vim -e /mnt/transcend/data/shs/1718/tab/tab/shs2017_td_home_work_public.tab < blanks_to_missing.vim
vim -e /mnt/transcend/data/shs/1718/tab/tab/shs2017_td_stage_public.tab < blanks_to_missing.vim
vim -e /mnt/transcend/data/shs/1718/tab/tab/shs2017_td_home_school_public.tab < blanks_to_missing.vim
vim -e /mnt/transcend/data/shs/1718/tab/tab/shs2017_social_public.tab < blanks_to_missing.vim
vim -e /mnt/transcend/data/shs/1718/tab/tab/shs2017_td_journey_public.tab < blanks_to_missing.vim
vim -e /mnt/transcend/data/shs/1819/tab/shs2018_td_journey_public.tab < blanks_to_missing.vim
vim -e /mnt/transcend/data/shs/1819/tab/shs2018_td_home_school_public.tab < blanks_to_missing.vim
vim -e /mnt/transcend/data/shs/1819/tab/shs2018_social_public.tab < blanks_to_missing.vim
vim -e /mnt/transcend/data/shs/1819/tab/shs2018_td_home_work_public.tab < blanks_to_missing.vim
vim -e /mnt/transcend/data/shs/1819/tab/shs2018_td_stage_public.tab < blanks_to_missing.vim
vim -e /mnt/transcend/data/shs/1617/tab/tab/shs2016_td_stage_public.tab < blanks_to_missing.vim
vim -e /mnt/transcend/data/shs/1617/tab/tab/shs2016_social_public.tab < blanks_to_missing.vim
vim -e /mnt/transcend/data/shs/1617/tab/tab/shs2016_td_home_school_public.tab < blanks_to_missing.vim
vim -e /mnt/transcend/data/shs/1617/tab/tab/shs2016_td_home_work_public.tab < blanks_to_missing.vim
vim -e /mnt/transcend/data/shs/1617/tab/tab/shs2016_td_journey_public.tab < blanks_to_missing.vim
