1,$s/BEREAVEMENT_ALLOWANCE bereavement_allowance//g
1,$s/DLA_MOBILITY/dla_mobility/g
1,$s/DLA_SELF_CARE/dla_self_care/g
1,$s/CONTRIB_EMPLOYMENT_AND_SUPPORT_ALLOWANCE/contrib_employment_and_support_allowance/g
1,$s/NON_CONTRIB_EMPLOYMENT_AND_SUPPORT_ALLOWANCE/non_contrib_employment_and_support_allowance/g
1,$s/SAVINGS_CREDIT/savings_credit/g
1,$s/CONTRIB_JOBSEEKERS_ALLOWANCE/contrib_job_seekers_allowance/g
1,$s/NON_CONTRIB_EMPLOYMENT_AND_SUPPORT_ALLOWANCE non_contrib_job_seekers_allowance//g
1,$s/COUNCIL_TAX_BENEFIT /council_tax_benefit/g
1,$s/OTHER_TAX/other_tax/g
1,$s/INDUSTRIAL_INJURY_BENEFIT/industrial_injury_disablement_benefit/g
1,$s/maternity_grant_from_social_fund/maternity_grant/g
1,$s/MATERNITY_GRANT/maternity_grant/g
1,$s/war_widows_or_widowers_pension/war_widows_pension/g
1,$s/WAR_WIDOWS_PENSION/war_widows_pension/g
1,$s/OTHER_SCOTTISH_BENEFITS/other_scottish_benefits/g
1,$s/BASIC_INCOME/basic_income/g
1,$s/FUNERAL_GRANT/funeral_grant/g
1,$s/ACCIDENT_INSURANCE_SCHEME_BENEFITS/accident_insurance_scheme_benefits/g
1,$s/ADP_DAILY_LIVING/adp_daily_living/g
1,$s/ADP_MOBILITY/adp_mobility/g
1,$s/ALIMONY_AND_CHILD_SUPPORT_PAID/alimony_and_child_support_paid/g
1,$s/ALIMONY_AND_CHILD_SUPPORT_RECEIVED/alimony_and_child_support_received/g
1,$s/ANY_OTHER_NI_OR_STATE_BENEFIT/any_other_ni_or_state_benefit/g
1,$s/ANY_OTHER_SICKNESS_INSURANCE/any_other_sickness_insurance/g
1,$s/ARMED_FORCES_COMPENSATION_SCHEME/armed_forces_compensation_scheme/g
1,$s/ATTENDANCE_ALLOWANCE/attendance_allowance/g
1,$s/AVCS/avcs/g
1,$s/BANK_INTEREST/bank_interest/g
1,$s/BONDS_AND_GILTS/bonds_and_gilts/g
1,$s/CARERS_ALLOWANCE/carers_allowance/g
1,$s/CARERS_ALLOWANCE_SUPPLEMENT/carers_allowance_supplement/g
1,$s/CARERS_SUPPORT_PAYMENT/carers_support_payment/g
1,$s/CARE_INSURANCE/care_insurance/g
1,$s/CHILD_BENEFIT/child_benefit/g
1,$s/CHILD_DISABILITY_PAYMENT_CARE/child_disability_payment_care/g
1,$s/CHILD_DISABILITY_PAYMENT_MOBILITY/child_disability_payment_mobility/g
1,$s/CHILD_TAX_CREDIT/child_tax_credit/g
1,$s/CRITICAL_ILLNESS_COVER/critical_illness_cover/g
1,$s/DISCRETIONARY_HOUSING_PAYMENT/discretionary_housing_payment/g
1,$s/EDUCATION_ALLOWANCES/education_allowances/g
1,$s/FOSTER_CARE_PAYMENTS/foster_care_payments/g
1,$s/FREE_SCHOOL_MEALS/free_school_meals/g
1,$s/FRIENDLY_SOCIETIES/friendly_societies/g
1,$s/FRIENDLY_SOCIETY_BENEFITS/friendly_society_benefits/g
1,$s/GOVERNMENT_TRAINING_ALLOWANCES/government_training_allowances/g
1,$s/GUARDIANS_ALLOWANCE/guardians_allowance/g
1,$s/HEALTH_INSURANCE/health_insurance/g
1,$s/HOSPITAL_SAVINGS_SCHEME_BENEFITS/hospital_savings_scheme_benefits/g
1,$s/HOUSING_BENEFIT/housing_benefit/g
1,$s/INCAPACITY_BENEFIT/incapacity_benefit/g
1,$s/INCOME_SUPPORT/income_support/g
1,$s/INCOME_TAX/income_tax/g
1,$s/INDIVIDUAL_SAVINGS_ACCOUNT/individual_savings_account/g
1,$s/LOAN_REPAYMENTS/loan_repayments/g
1,$s/LOCAL_TAXES/local_taxes/g
1,$s/MATERNITY_ALLOWANCE/maternity_allowance/g
1,$s/NATIONAL_INSURANCE/national_insurance/g
1,$s/NATIONAL_SAVINGS/national_savings/g
1,$s/ODD_JOBS/odd_jobs/g
1,$s/OTHER_BENEFITS/other_benefits/g
1,$s/OTHER_DEDUCTIONS/other_deductions/g
1,$s/OTHER_INCOME/other_income/g
1,$s/OTHER_INVESTMENT_INCOME/other_investment_income/g
1,$s/PENSION_AGE_DISABILITY/pension_age_disability/g
1,$s/PENSION_CONTRIBUTIONS_EMPLOYEE/pension_contributions_employee/g
1,$s/PENSION_CONTRIBUTIONS_EMPLOYER/pension_contributions_employer/g
1,$s/PENSION_CREDIT/pension_credit/g
1,$s/PERMANENT_HEALTH_INSURANCE/permanent_health_insurance/g
1,$s/PERSONAL_INDEPENDENCE_PAYMENT_DAILY_LIVING/personal_independence_payment_daily_living/g
1,$s/PERSONAL_INDEPENDENCE_PAYMENT_MOBILITY/personal_independence_payment_mobility/g
1,$s/PRIVATE_PENSIONS/private_pensions/g
1,$s/PRIVATE_SICKNESS_SCHEME_BENEFITS/private_sickness_scheme_benefits/g
1,$s/PROPERTY/property/g
1,$s/ROYALTIES/royalties/g
1,$s/SCOTTISH_CHILD_PAYMENT/scottish_child_payment/g
1,$s/SELF_EMPLOYMENT_INCOME/self_employment_income/g
1,$s/SEVERE_DISABILITY_ALLOWANCE/severe_disability_allowance/g
1,$s/STATE_PENSION/state_pension/g
1,$s/STOCKS_SHARES/stocks_shares/g
1,$s/STUDENT_GRANTS/student_grants/g
1,$s/STUDENT_LOANS/student_loans/g
1,$s/STUDENT_LOAN_REPAYMENTS/student_loan_repayments/g
1,$s/TRADE_UNIONS_ETC/trade_unions_etc/g
1,$s/TRADE_UNION_SICK_OR_STRIKE_PAY/trade_union_sick_or_strike_pay/g
1,$s/UNEMPLOYMENT_OR_REDUNDANCY_INSURANCE/unemployment_or_redundancy_insurance/g
1,$s/UNIVERSAL_CREDIT/universal_credit/g
1,$s/WAGES/wages/g
1,$s/WIDOWS_PAYMENT/widows_payment/g
1,$s/WINTER_FUEL_PAYMENTS/winter_fuel_payments/g
1,$s/WORKING_TAX_CREDIT/working_tax_credit/g
1,$s/WORK_EXPENSES/work_expenses/g

:write
:quit

