#!/bin/sh
/bin/cp -f web/*.html /var/www/stb/
/bin/cp -f web/js/stb-support.js /var/www/stb/js/
/bin/cp -arf web/images /var/www/stb/
/bin/cp -f web/css/stb.css /var/www/stb/css/
/bin/cp -arf book/build/ /var/www/stb/
