using ScottishTaxBenefitModel
using Documenter

makedocs(;
    modules=[
        ScottishTaxBenefitModel, 
        ScottishTaxBenefitModel.BCCalcs,
        ScottishTaxBenefitModel.BenefitCap,
        ScottishTaxBenefitModel.BenefitGenerosity,
        # ScottishTaxBenefitModel.DataUtils,
        ScottishTaxBenefitModel.Definitions,
        ScottishTaxBenefitModel.EquivalenceScales,
        ScottishTaxBenefitModel.ExampleHelpers,
        ScottishTaxBenefitModel.ExampleHouseholdGetter,
        ScottishTaxBenefitModel.Expenditure,
        
        #  ScottishTaxBenefitModel.ExampleTable,
        ScottishTaxBenefitModel.FRSHouseholdGetter,
        ScottishTaxBenefitModel.GeneralTaxComponents,
        ScottishTaxBenefitModel.HistoricBenefits,
        ScottishTaxBenefitModel.HouseholdFromFrame,
        # HouseholdMappingFRS_HBAI_Pre_2019,
        # HouseholdMappingFRS_HBAI,
        ScottishTaxBenefitModel.IncomeTaxCalculations,
        ScottishTaxBenefitModel.Intermediate,
        ScottishTaxBenefitModel.LegacyMeansTestedBenefits,
        ScottishTaxBenefitModel.LocalLevelCalculations,
        # ScottishTaxBenefitModel.MiniTB,
        ScottishTaxBenefitModel.ModelHousehold,
        ScottishTaxBenefitModel.Monitor,
        ScottishTaxBenefitModel.NationalInsuranceCalculations,
        ScottishTaxBenefitModel.NonMeansTestedBenefits,
        # ScottishTaxBenefitModel.ParamsIO,
        ScottishTaxBenefitModel.Pensions,
        ScottishTaxBenefitModel.Randoms,
        ScottishTaxBenefitModel.Results,
        ScottishTaxBenefitModel.Runner,
        ScottishTaxBenefitModel.RunSettings,
        ScottishTaxBenefitModel.ScottishBenefits,
        ScottishTaxBenefitModel.ScottishTaxBenefitModel,
        ScottishTaxBenefitModel.SimplePovertyCounts,
        ScottishTaxBenefitModel.SingleHouseholdCalculations,
        ScottishTaxBenefitModel.STBIncomes,
        ScottishTaxBenefitModel.STBOutput,
        ScottishTaxBenefitModel.STBParameters,
        # ScottishTaxBenefitModel.STBUnits,
        ScottishTaxBenefitModel.TheEqualiser,
        ScottishTaxBenefitModel.TimeSeriesUtils,
        ScottishTaxBenefitModel.UBI,
        ScottishTaxBenefitModel.UCTransition,
        ScottishTaxBenefitModel.UniversalCredit,
        ScottishTaxBenefitModel.Uprating,
        ScottishTaxBenefitModel.Utils,
        ScottishTaxBenefitModel.Weighting,
        ScottishTaxBenefitModel.HouseholdAdjuster,
        ScottishTaxBenefitModel.ConsumptionData,
        ScottishTaxBenefitModel.Expenditure,
        ScottishTaxBenefitModel.HealthRegressions,
        ScottishTaxBenefitModel.HouseholdAdjuster,
        ScottishTaxBenefitModel.HTMLLibs,
        ScottishTaxBenefitModel.LegalAidCalculations,
        ScottishTaxBenefitModel.LegalAidOutput,
        ScottishTaxBenefitModel.MatchingLibs,
        ScottishTaxBenefitModel.OtherTaxes,
        ScottishTaxBenefitModel.STBIncomes,
        ScottishTaxBenefitModel.Utils,
        ScottishTaxBenefitModel.WealthData],
    authors="Graham Stark",
    # checkdocs=:exports,
    repo="https://github.com/grahamstark/ScottishTaxBenefitModel.jl/blob/{commit}{path}#L{line}",
    sitename="ScottishTaxBenefitModel.jl",
    format=Documenter.HTML(;
        prettyurls=get(ENV, "CI", "false") == "true",
        canonical="https://grahamstark.github.io/ScottishTaxBenefitModel.jl",
        assets=String[],
    ),
    pages=[
        "Home" => "index.md",
        "Global Definition Modules" => "globals.md",
        "Main Calculation Modules" => "main-calculations.md",
        "Household Modules" => "households.md",
        "Support Modules" => "support.md",
        "Module Listing" => "module_listing.md",
        "Weighting Notes" => "weighting.md",
        "Annotated Bibliography" => "annotated_bibliography.md",
        "Test Suite" => "test_suite.md",
        "Validation in Aggregate" => "validation_in_aggregate.md",
        "Coding Notes" => "coding_notes.md",
        "TODO" => "TODO.md"
    ],
)

deploydocs(;
    repo="github.com/grahamstark/ScottishTaxBenefitModel.jl",
)
