module Incomes
    
    using Definitions
    using StaticArrays

    # declarations  ----------------
    const WAGES = 1
    const SELF_EMPLOYMENT_INCOME = 2
    const ODD_JOBS = 3
    const PRIVATE_PENSIONS = 4
    const NATIONAL_SAVINGS = 5
    const BANK_INTEREST = 6
    const STOCKS_SHARES = 7
    const INDIVIDUAL_SAVINGS_ACCOUNT = 8
    const PROPERTY = 9
    const ROYALTIES = 10
    const BONDS_AND_GILTS = 11
    const OTHER_INVESTMENT_INCOME = 12
    const OTHER_INCOME = 13
    const ALIMONY_AND_CHILD_SUPPORT_RECEIVED = 14
    const PRIVATE_SICKNESS_SCHEME_BENEFITS = 15
    const ACCIDENT_INSURANCE_SCHEME_BENEFITS = 16
    const HOSPITAL_SAVINGS_SCHEME_BENEFITS = 17
    const UNEMPLOYMENT_OR_REDUNDANCY_INSURANCE = 18
    const PERMANENT_HEALTH_INSURANCE = 19
    const ANY_OTHER_SICKNESS_INSURANCE = 20
    const CRITICAL_ILLNESS_COVER = 21
    const TRADE_UNION_SICK_OR_STRIKE_PAY = 22
    const SPARE_INC_1 = 23
    const SPARE_INC_2 = 24
    const SPARE_INC_3 = 25
    const SPARE_INC_4 = 26
    const SPARE_INC_5 = 27
    const HEALTH_INSURANCE = 28
    const ALIMONY_AND_CHILD_SUPPORT_PAID = 29
    const TRADE_UNIONS_ETC = 30
    const FRIENDLY_SOCIETIES = 31
    const WORK_EXPENSES = 32
    const AVCS = 33
    const OTHER_DEDUCTIONS = 34
    const LOAN_REPAYMENTS = 35
    const PENSION_CONTRIBUTIONS_EMPLOYEE = 36
    const PENSION_CONTRIBUTIONS_EMPLOYER = 37
    const SPARE_DEDUCT_1 = 38
    const SPARE_DEDUCT_2 = 39
    const SPARE_DEDUCT_3 = 40
    const SPARE_DEDUCT_4 = 41
    const SPARE_DEDUCT_5 = 42
    const INCOME_TAX = 43
    const NATIONAL_INSURANCE = 44
    const LOCAL_TAXES = 45
    const SOCIAL_FUND_LOAN_REPAYMENT = 46
    const STUDENT_LOAN_REPAYMENTS = 47
    const CARE_INSURANCE = 48
    const SPARE_TAX_1 = 49
    const SPARE_TAX_2 = 50
    const SPARE_TAX_3 = 51
    const SPARE_TAX_4 = 52
    const SPARE_TAX_5 = 53
    const CHILD_BENEFIT = 54
    const STATE_PENSION = 55
    const BEREAVEMENT_ALLOWANCE = 56
    const ARMED_FORCES_COMPENSATION_SCHEME = 57
    const WAR_WIDOWS_PENSION = 58
    const SEVERE_DISABILITY_ALLOWANCE = 59
    const ATTENDENCE_ALLOWANCE = 60
    const CARERS_ALLOWANCE = 61
    const INDUSTRIAL_INJURY_BENEFIT = 62
    const INCAPACITY_BENEFIT = 63
    const PERSONAL_INDEPENDENCE_PAYMENT_DAILY_LIVING = 64
    const PERSONAL_INDEPENDENCE_PAYMENT_MOBILITY = 65
    const DLA_SELF_CARE = 66
    const DLA_MOBILITY = 67
    const EDUCATION_ALLOWANCES = 68
    const FOSTER_CARE_PAYMENTS = 69
    const MATERNITY_ALLOWANCE = 70
    const MATERNITY_GRANT = 71
    const FUNERAL_GRANT = 72
    const ANY_OTHER_NI_OR_STATE_BENEFIT = 73
    const FRIENDLY_SOCIETY_BENEFITS = 74
    const GOVERNMENT_TRAINING_ALLOWANCES = 75
    const CONTRIB_JOBSEEKERS_ALLOWANCE = 76
    const GUARDIANS_ALLOWANCE = 77
    const WIDOWS_PAYMENT = 78
    const WINTER_FUEL_PAYMENTS = 79
    const WORKING_TAX_CREDIT = 80
    const CHILD_TAX_CREDIT = 81
    const EMPLOYMENT_AND_SUPPORT_ALLOWANCE = 82
    const INCOME_SUPPORT = 83
    const PENSION_CREDIT = 84
    const SAVINGS_CREDIT = 85
    const NON_CONTRIB_JOBSEEKERS_ALLOWANCE = 86
    const HOUSING_BENEFIT = 87
    const FREE_SCHOOL_MEALS = 88
    const UNIVERSAL_CREDIT = 89
    const OTHER_BENEFITS = 90
    const STUDENT_GRANTS = 91
    const STUDENT_LOANS = 92
    const SPARE_BEN_1 = 93
    const SPARE_BEN_2 = 94
    const SPARE_BEN_3 = 95
    const SPARE_BEN_4 = 96
    const SPARE_BEN_5 = 97


    # exports ----------------
    export WAGES
    export SELF_EMPLOYMENT_INCOME
    export ODD_JOBS
    export PRIVATE_PENSIONS
    export NATIONAL_SAVINGS
    export BANK_INTEREST
    export STOCKS_SHARES
    export INDIVIDUAL_SAVINGS_ACCOUNT
    export PROPERTY
    export ROYALTIES
    export BONDS_AND_GILTS
    export OTHER_INVESTMENT_INCOME
    export OTHER_INCOME
    export ALIMONY_AND_CHILD_SUPPORT_RECEIVED
    export PRIVATE_SICKNESS_SCHEME_BENEFITS
    export ACCIDENT_INSURANCE_SCHEME_BENEFITS
    export HOSPITAL_SAVINGS_SCHEME_BENEFITS
    export UNEMPLOYMENT_OR_REDUNDANCY_INSURANCE
    export PERMANENT_HEALTH_INSURANCE
    export ANY_OTHER_SICKNESS_INSURANCE
    export CRITICAL_ILLNESS_COVER
    export TRADE_UNION_SICK_OR_STRIKE_PAY
    export SPARE_INC_1
    export SPARE_INC_2
    export SPARE_INC_3
    export SPARE_INC_4
    export SPARE_INC_5
    export HEALTH_INSURANCE
    export ALIMONY_AND_CHILD_SUPPORT_PAID
    export TRADE_UNIONS_ETC
    export FRIENDLY_SOCIETIES
    export WORK_EXPENSES
    export AVCS
    export OTHER_DEDUCTIONS
    export LOAN_REPAYMENTS
    export PENSION_CONTRIBUTIONS_EMPLOYEE
    export PENSION_CONTRIBUTIONS_EMPLOYER
    export SPARE_DEDUCT_1
    export SPARE_DEDUCT_2
    export SPARE_DEDUCT_3
    export SPARE_DEDUCT_4
    export SPARE_DEDUCT_5
    export INCOME_TAX
    export NATIONAL_INSURANCE
    export LOCAL_TAXES
    export SOCIAL_FUND_LOAN_REPAYMENT
    export STUDENT_LOAN_REPAYMENTS
    export CARE_INSURANCE
    export SPARE_TAX_1
    export SPARE_TAX_2
    export SPARE_TAX_3
    export SPARE_TAX_4
    export SPARE_TAX_5
    export CHILD_BENEFIT
    export STATE_PENSION
    export BEREAVEMENT_ALLOWANCE
    export ARMED_FORCES_COMPENSATION_SCHEME
    export WAR_WIDOWS_PENSION
    export SEVERE_DISABILITY_ALLOWANCE
    export ATTENDENCE_ALLOWANCE
    export CARERS_ALLOWANCE
    export INDUSTRIAL_INJURY_BENEFIT
    export INCAPACITY_BENEFIT
    export PERSONAL_INDEPENDENCE_PAYMENT_DAILY_LIVING
    export PERSONAL_INDEPENDENCE_PAYMENT_MOBILITY
    export DLA_SELF_CARE
    export DLA_MOBILITY
    export EDUCATION_ALLOWANCES
    export FOSTER_CARE_PAYMENTS
    export MATERNITY_ALLOWANCE
    export MATERNITY_GRANT
    export FUNERAL_GRANT
    export ANY_OTHER_NI_OR_STATE_BENEFIT
    export FRIENDLY_SOCIETY_BENEFITS
    export GOVERNMENT_TRAINING_ALLOWANCES
    export CONTRIB_JOBSEEKERS_ALLOWANCE
    export GUARDIANS_ALLOWANCE
    export WIDOWS_PAYMENT
    export WINTER_FUEL_PAYMENTS
    export WORKING_TAX_CREDIT
    export CHILD_TAX_CREDIT
    export EMPLOYMENT_AND_SUPPORT_ALLOWANCE
    export INCOME_SUPPORT
    export PENSION_CREDIT
    export SAVINGS_CREDIT
    export NON_CONTRIB_JOBSEEKERS_ALLOWANCE
    export HOUSING_BENEFIT
    export FREE_SCHOOL_MEALS
    export UNIVERSAL_CREDIT
    export OTHER_BENEFITS
    export STUDENT_GRANTS
    export STUDENT_LOANS
    export SPARE_BEN_1
    export SPARE_BEN_2
    export SPARE_BEN_3
    export SPARE_BEN_4
    export SPARE_BEN_5


end